meta_product_name: "JumpIn"
meta_title: "Jump In Bordeaux"
meta_description: "On vous donne le timming du prochain tram/bus/bateau en deux cliques"
meta_image: "faviconjumpin.png" # should exist in `app/assets/images/`
